#ifndef TEST_APP_DEFINITIONS
#define TEST_APP_DEFINITIONS


#include "base_types/macros/definition.hpp"


#define TEST_APP_AUTHOR NO_BASES_DATACLASS_DEFINITION(\
    TEST_APP_AUTHOR,\
    (test_app, author),\
    (DATACLASS_MEMBER(BTP_INT8, id))\
    (DATACLASS_MEMBER(BTP_TEXT, name))\
)
#define TEST_APP_AUTHOR_MEMBERS T_DIRECT_MEMBERS(TEST_APP_AUTHOR)
#define TEST_APP_AUTHOR_CONSTRUCTORS (TEST_APP_AUTHOR)


#define TEST_APP_AUTHORED NO_BASES_DATACLASS_DEFINITION(\
    TEST_APP_AUTHORED,\
    (test_app, authored),\
    (DATACLASS_MEMBER(BTP_INT8, author_id))\
    (DATACLASS_MEMBER(BTP_TEXT, content))\
)
#define TEST_APP_AUTHORED_MEMBERS T_DIRECT_MEMBERS(TEST_APP_AUTHORED)
#define TEST_APP_AUTHORED_CONSTRUCTORS (TEST_APP_AUTHORED)


#define TEST_APP_WITH_TIMESTAMPS NO_BASES_DATACLASS_DEFINITION(\
    TEST_APP_WITH_TIMESTAMPS,\
    (test_app, with_timestamps),\
    (DATACLASS_MEMBER(BTP_TIMESTAMPTZ, created_at))\
    (DATACLASS_MEMBER(BTP_TIMESTAMPTZ, updated_at))\
)
#define TEST_APP_WITH_TIMESTAMPS_MEMBERS T_DIRECT_MEMBERS(TEST_APP_WITH_TIMESTAMPS)
#define TEST_APP_WITH_TIMESTAMPS_CONSTRUCTORS (TEST_APP_WITH_TIMESTAMPS)


#define TEST_APP_POST_STATUS ENUM_DEFINITION(\
    TEST_APP_POST_STATUS,\
    (test_app, post_status),\
    (ENUM_MEMBER(published))\
    (ENUM_MEMBER(waiting_approval))\
    (ENUM_MEMBER(draft))\
)
#define TEST_APP_POST_STATUS_CONSTRUCTORS (TEST_APP_POST_STATUS)


#define TEST_APP_POST DATACLASS_DEFINITION(\
    TEST_APP_POST,\
    (test_app, post),\
    (DATACLASS_MEMBER(BTP_INT8, id))\
    (DATACLASS_MEMBER(BTP_TEXT, title))\
    (DATACLASS_MEMBER(TEST_APP_POST_STATUS, status)),\
    (TEST_APP_AUTHORED)(TEST_APP_WITH_TIMESTAMPS)\
)
#define TEST_APP_POST_MEMBERS T_DIRECT_MEMBERS(TEST_APP_POST)\
    TEST_APP_AUTHORED_MEMBERS\
    TEST_APP_WITH_TIMESTAMPS_MEMBERS
#define TEST_APP_POST_CONSTRUCTORS (TEST_APP_POST)


#define TEST_APP_COMMENT DATACLASS_DEFINITION(\
    TEST_APP_COMMENT,\
    (test_app, comment),\
    (DATACLASS_MEMBER(BTP_INT8, id))\
    (DATACLASS_MEMBER(BTP_INT8, post_id)),\
    (TEST_APP_AUTHORED)(TEST_APP_WITH_TIMESTAMPS)\
)
#define TEST_APP_COMMENT_MEMBERS T_DIRECT_MEMBERS(TEST_APP_COMMENT)\
    TEST_APP_AUTHORED_MEMBERS\
    TEST_APP_WITH_TIMESTAMPS_MEMBERS
#define TEST_APP_COMMENT_CONSTRUCTORS (TEST_APP_COMMENT)


#define TEST_APP_COMMENT_POST NO_BASES_DATACLASS_DEFINITION(\
    TEST_APP_COMMENT_POST,\
    (test_app, comment_post),\
    (DATACLASS_MEMBER(TEST_APP_COMMENT, comment))\
    (DATACLASS_MEMBER(TEST_APP_POST, post))\
    (DATACLASS_MEMBER(BTP_TEXT, description))\
    (DATACLASS_MEMBER(TEST_APP_AUTHOR, author))\
)
#define TEST_APP_COMMENT_POST_MEMBERS T_DIRECT_MEMBERS(TEST_APP_COMMENT_POST)
#define TEST_APP_COMMENT_POST_CONSTRUCTORS (TEST_APP_COMMENT_POST)


#define TEST_APP_DOMAIN TYPE_DEFINITION_ALIAS(\
    TEST_APP_DOMAIN,\
    (test_app, domain),\
    BTP_INT8\
)
#define TEST_APP_DOMAIN_CONSTRUCTORS (TEST_APP_DOMAIN) BTP_INT8_CONSTRUCTORS
#define TEST_APP_DOMAIN_INHERITANCE_CHAIN (BTP_INT8)


#endif
