#ifndef BASE_TYPES_DEFINITION_BASE
#define BASE_TYPES_DEFINITION_BASE


#include <boost/preprocessor.hpp>
#include <boost/preprocessor/iteration/iterate.hpp>
#include <boost/preprocessor/facilities/empty.hpp> 
#include <boost/preprocessor/stringize.hpp>
#include <boost/preprocessor/cat.hpp>


#define DATACLASS_MEMBER(BASE_TP, NAME)(\
    T_NAMETUPLE(BASE_TP),\
    NAME,\
    0\
)


#define OPTIONAL_DATACLASS_MEMBER(TP_NAMESPACE, TP_NAME, NAME)(\
    (TP_NAMESPACE, TP_NAME),\
    NAME,\
    1\
)


#define DATACLASS_DEFINITION(NAME, CLS, MEMBERS, BASES)(\
    NAME,\
    CLS,\
    MEMBERS,\
    BASES\
)


#define NO_BASES_DATACLASS_DEFINITION(NAME, CLS, MEMBERS)\
    DATACLASS_DEFINITION(NAME, CLS, MEMBERS, BOOST_PP_EMPTY())


#define ENUM_MEMBER(NAME) NAME


#define ENUM_QUALIFIED_UNDERLYING_CLASS(ENUM_DEF)\
    BOOST_PP_TUPLE_ELEM(2, ENUM_DEF)


#define ENUM_UNQUALIFIED_UNDERLYING_CLASS(ENUM_DEF)\
    BOOST_PP_CAT(T_NAME(T_NAMETUPLE(ENUM_DEF)), _enum)


#define ENUM_MEMBERS(ENUM_DEF)\
    BOOST_PP_TUPLE_ELEM(4, ENUM_DEF)


#define ENUM_DEFINITION(NAME, CLS, MEMBERS)(\
    NAME,\
    CLS,\
    BOOST_PP_CAT(T_QUALNAME(CLS), _enum),\
    BOOST_PP_EMPTY(),\
    MEMBERS\
)


#define T_BASE_PRIMITIVE(TYPE_DEF)\
    BOOST_PP_TUPLE_ELEM(2, TYPE_DEF)


#define T_PY_PRIMITIVE(TYPE_DEF)\
    BOOST_PP_TUPLE_ELEM(3, TYPE_DEF)


#define TYPE_DEFINITION(NAME, CLS, BASE_PRIMITIVE, LINK_PRIMITIVE)(\
    NAME,\
    CLS,\
    BASE_PRIMITIVE,\
    LINK_PRIMITIVE\
)


#define T_ALIAS_BASE(ALIAS_DEF)\
    BOOST_PP_TUPLE_ELEM(4, ALIAS_DEF)


#define T_CONSTRUCTORS(TYPE_DEF)\
    BOOST_PP_CAT(T_MACRO_NAME(TYPE_DEF), _CONSTRUCTORS)


#define T_ALIAS_INHERITANCE_CHAIN(ALIAS_DEF)\
    BOOST_PP_CAT(T_MACRO_NAME(ALIAS_DEF), _INHERITANCE_CHAIN)


#define T_ALIAS_ORIGIN(ALIAS_DEF)\
    BOOST_PP_SEQ_HEAD(T_ALIAS_INHERITANCE_CHAIN(ALIAS_DEF))


#define TYPE_DEFINITION_ALIAS(NAME, CLS, BASE)(\
    NAME,\
    CLS,\
    T_BASE_PRIMITIVE(BASE),\
    T_PY_PRIMITIVE(BASE),\
    BASE\
)


#define ENUM_DEFINITION_ALIAS(NAME, CLS, BASE)(\
    NAME,\
    CLS,\
    T_BASE_PRIMITIVE(BASE),\
    BOOST_PP_EMPTY(),\
    BASE\
)


#define DATACLASS_DEFINITION_ALIAS(NAME, CLS, BASE)(\
    NAME,\
    CLS,\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BASE\
)


#define OVERLOAD_PARAMETER(TP_NAMESPACE, TP_NAME, NAME)\
    (TP_NAMESPACE, TP_NAME),\
    NAME\
)


#define T_MACRO_NAME(TYPE_DEF)\
    BOOST_PP_TUPLE_ELEM(0, TYPE_DEF)


#define T_NAMESPACE(NAMETUPLE)\
    BOOST_PP_TUPLE_ELEM(0, NAMETUPLE)


#define T_NAME(NAMETUPLE)\
    BOOST_PP_TUPLE_ELEM(1, NAMETUPLE)


#define T_NAMETUPLE(TYPE_DEF)\
    BOOST_PP_TUPLE_ELEM(1, TYPE_DEF)


#define T_QUALNAME(TYPE_DEF)\
    T_NAMESPACE(TYPE_DEF)::T_NAME(TYPE_DEF)


#define T_DIRECT_MEMBERS(CLASS_DEF)\
    BOOST_PP_TUPLE_ELEM(2, CLASS_DEF)


#define T_BASES(CLASS_DEF)\
    BOOST_PP_TUPLE_ELEM(3, CLASS_DEF)


#define CM_NAME(CLASS_MEMBER)\
    BOOST_PP_TUPLE_ELEM(1, CLASS_MEMBER)


#define CM_TYPE(CLASS_MEMBER)\
    BOOST_PP_TUPLE_ELEM(0, CLASS_MEMBER)


#define CM_IS_OPTIONAL(CLASS_MEMBER)\
    BOOST_PP_TUPLE_ELEM(2, CLASS_MEMBER)


#define CM_QUALIFIED_TYPE(CLASS_MEMBER)\
    BOOST_PP_IF(\
        CM_IS_OPTIONAL(CLASS_MEMBER),\
        std::optional<T_QUALNAME(CM_TYPE(CLASS_MEMBER))>,\
        T_QUALNAME(CM_TYPE(CLASS_MEMBER))\
    )


#define C_ALL_MEMBERS(CLASS_DEF)\
    BOOST_PP_SEQ_CAT((T_MACRO_NAME(CLASS_DEF))(_MEMBERS))


#endif
