#ifndef CORE_TYPES_MACROS_REGISTER_DESCRIPTIVE
#define CORE_TYPES_MACROS_REGISTER_DESCRIPTIVE
#include "core_types/macros/register/_base.hpp"

 
#define CT_CLASSDEF_REGISTER_DESCRIPTIVE(CLASS_DEF, m)\
CT_CLASSDEF_REGISTER_BASE(CLASS_DEF, m)


#define CT_CLASS_ALIASDEF_REGISTER_DESCRIPTIVE(ALIAS_DEF, m)\
CT_CLASS_ALIASDEF_REGISTER_BASE(ALIAS_DEF, m)


#define CT_TYPEDEF_REGISTER_DESCRIPTIVE(TYPE_DEF, m)\
CT_TYPEDEF_REGISTER_BASE(TYPE_DEF, m)


#define CT_TYPE_ALIASDEF_REGISTER_DESCRIPTIVE(ALIAS_DEF, m)\
CT_TYPE_ALIASDEF_REGISTER_BASE(ALIAS_DEF, m)


#define CT_ENUMDEF_REGISTER_DESCRIPTIVE(ENUM_DEF, m)\
CT_ENUMDEF_REGISTER_BASE(ENUM_DEF, m)


#define CT_ENUM_ALIASDEF_REGISTER_DESCRIPTIVE(ALIAS_DEF, m)\
CT_ENUM_ALIASDEF_REGISTER_BASE(ALIAS_DEF, m)

#endif
