#ifndef CORE_TYPES_MACROS_REGISTER_INSTANCEABLE
#define CORE_TYPES_MACROS_REGISTER_INSTANCEABLE
#include "core_types/macros/register/_base.hpp"


#define CT_CLASSDEF_REGISTER_INSTANCEABLE(CLASS_DEF, m)\
CT_CLASSDEF_REGISTER_BASE(CLASS_DEF, m)\
BOOST_PP_SEQ_FOR_EACH(C_PY_CONSTRUCTOR, BOOST_PP_EMPTY(), T_CONSTRUCTORS(CLASS_DEF))\
.def("to_py", &T_QUALNAME(T_IFACE_TYPE(CLASS_DEF))::to_py)


#define CT_CLASS_ALIASDEF_REGISTER_INSTANCEABLE(ALIAS_DEF, m, CONSTRUCTORS)\
CT_CLASS_ALIASDEF_REGISTER_BASE(ALIAS_DEF, m)\
BOOST_PP_SEQ_FOR_EACH(C_PY_CONSTRUCTOR, BOOST_PP_EMPTY(), CONSTRUCTORS)\
.def("to_py", &T_QUALNAME(T_IFACE_TYPE(ALIAS_DEF))::to_py)


#define CT_TYPEDEF_REGISTER_INSTANCEABLE(TYPE_DEF, m, CONSTRUCTORS)\
CT_TYPEDEF_REGISTER_BASE(TYPE_DEF, m)\
TD_PY_TYPE_CONSTRUCTORS(TYPE_DEF, CONSTRUCTORS)\
.def("to_py", &T_QUALNAME(T_IFACE_TYPE(TYPE_DEF))::to_py)\
.def("compare", [](const T_QUALNAME(T_IFACE_TYPE(TYPE_DEF))& t, const T_PY_PRIMITIVE(TYPE_DEF)& other) {\
    T_QUALNAME(T_IFACE_TYPE(TYPE_DEF)) v(other.attr("__str__")().cast<core_types::text>());\
    return t.compare<T_QUALIFIED_UNDERLYING_CLASS(TYPE_DEF)>(v);\
})\
BOOST_PP_SEQ_FOR_EACH(TD_DECLARE_COMPARE, TYPE_DEF, CONSTRUCTORS)


#define CT_TYPE_ALIASDEF_REGISTER_INSTANCEABLE(ALIAS_DEF, m, CONSTRUCTORS)\
CT_TYPE_ALIASDEF_REGISTER_BASE(ALIAS_DEF, m)\
TD_PY_TYPE_CONSTRUCTORS(ALIAS_DEF, CONSTRUCTORS)\
.def("to_py", &T_QUALNAME(T_IFACE_TYPE(ALIAS_DEF))::to_py)\
.def("compare", [](const T_QUALNAME(T_IFACE_TYPE(ALIAS_DEF))& t, const T_PY_PRIMITIVE(ALIAS_DEF)& other) {\
    T_QUALNAME(T_IFACE_TYPE(ALIAS_DEF)) v(other.attr("__str__")().cast<core_types::text>());\
    return t.compare<T_QUALIFIED_UNDERLYING_CLASS(ALIAS_DEF)>(v);\
})\
BOOST_PP_SEQ_FOR_EACH(TD_DECLARE_COMPARE, ALIAS_DEF, CONSTRUCTORS)


#define CT_ENUMDEF_REGISTER_INSTANCEABLE(ENUM_DEF, m)\
CT_ENUMDEF_REGISTER_BASE(ENUM_DEF, m)\
BOOST_PP_SEQ_FOR_EACH(ED_PY_COPY_CONSTRUCTOR, BOOST_PP_EMPTY(), T_CONSTRUCTORS(ENUM_DEF))\
.def(py::init([](const T_QUALNAME(T_NAMETUPLE(ENUM_DEF))& other){\
    return std::unique_ptr<T_QUALNAME(T_IFACE_TYPE(ENUM_DEF))>(\
        new T_QUALNAME(T_IFACE_TYPE(ENUM_DEF))(other));\
}))\
.def("to_py", &T_QUALNAME(T_IFACE_TYPE(ENUM_DEF))::to_py)
// BOOST_PP_SEQ_FOR_EACH(TD_DECLARE_COMPARE, ENUM_DEF, T_CONSTRUCTORS(ENUM_DEF))


#define CT_ENUM_ALIASDEF_REGISTER_INSTANCEABLE(ALIAS_DEF, m, CONSTRUCTORS)\
CT_ENUM_ALIASDEF_REGISTER_BASE(ALIAS_DEF, m, CONSTRUCTORS)\
BOOST_PP_SEQ_FOR_EACH(ED_PY_COPY_CONSTRUCTOR, BOOST_PP_EMPTY(), CONSTRUCTORS)\
.def(py::init([](const T_QUALIFIED_UNDERLYING_CLASS(ALIAS_DEF)& other){\
    return std::unique_ptr<T_QUALNAME(T_IFACE_TYPE(ALIAS_DEF))>(\
        new T_QUALNAME(T_IFACE_TYPE(ALIAS_DEF))(other));\
}))\
.def("to_py", &T_QUALNAME(T_IFACE_TYPE(ALIAS_DEF))::to_py)
// BOOST_PP_SEQ_FOR_EACH(TD_DECLARE_COMPARE, ALIAS_DEF, CONSTRUCTORS)

#endif
