#include "../include/base_types/macros/definition.hpp"
#include "../include/base_types/macros/register.hpp"
#include "../include/base_types/types.hpp"


PY_TYPEDEF_DECLARE_SUBCLASS_REG(BTP_BOOLEAN);
PY_TYPEDEF_DECLARE_SUBCLASS_REG(BTP_INT1);
PY_TYPEDEF_DECLARE_SUBCLASS_REG(BTP_INT2);
PY_TYPEDEF_DECLARE_SUBCLASS_REG(BTP_INT4);
PY_TYPEDEF_DECLARE_SUBCLASS_REG(BTP_INT8);
PY_TYPEDEF_DECLARE_SUBCLASS_REG(BTP_FLOAT4);
PY_TYPEDEF_DECLARE_SUBCLASS_REG(BTP_FLOAT8);
PY_TYPEDEF_DECLARE_SUBCLASS_REG(BTP_TIMESTAMPTZ);
PY_TYPEDEF_DECLARE_SUBCLASS_REG(BTP_DATE);
PY_TYPEDEF_DECLARE_SUBCLASS_REG(BTP_TEXT);
