#ifndef CORE_TYPES_MACROS_DEFINITION
#define CORE_TYPES_MACROS_DEFINITION
#include <boost/preprocessor.hpp>
#include <boost/preprocessor/iteration/iterate.hpp>
#include <boost/preprocessor/facilities/empty.hpp> 
#include <boost/preprocessor/stringize.hpp>
#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/logical/or.hpp>
#include <boost/type_index.hpp>


// NOTE IDENTIFIERS, CONTAINERS MUST BE 0
#define CT_STD_CONTAINER              0
#define CT_STD_OPTIONAL_IDENTIFIER    CT_STD_CONTAINER
#define CT_STD_VECTOR_IDENTIFIER      CT_STD_CONTAINER
#define CT_STD_DEQUE_IDENTIFIER       CT_STD_CONTAINER
#define CT_TYPEDEF_IDENTIFIER         1
#define CT_CLASSDEF_IDENTIFIER        2
#define CT_ENUMDEF_IDENTIFIER         3
#define CT_TYPEDEF_ALIAS_IDENTIFIER   4
#define CT_CLASSDEF_ALIAS_IDENTIFIER  5
#define CT_ENUMDEF_ALIAS_IDENTIFIER   6
#define CT_FUNCDEF_IDENTIFIER         7


// NOTE TYPE DEFINITION METHODS
#define T_MACRO_NAME(TYPE_DEF)\
BOOST_PP_TUPLE_ELEM(0, TYPE_DEF)


#define T_NAMETUPLE(TYPE_DEF)\
BOOST_PP_TUPLE_ELEM(1, TYPE_DEF)


#define T_BASE_PRIMITIVE(TYPE_DEF)\
BOOST_PP_TUPLE_ELEM(2, TYPE_DEF)


#define T_PY_PRIMITIVE(TYPE_DEF)\
BOOST_PP_TUPLE_ELEM(3, TYPE_DEF)


#define T_MEMBERS(TYPE_DEF)\
BOOST_PP_TUPLE_ELEM(4, TYPE_DEF)


#define T_BASE(TYPE_DEF)\
BOOST_PP_TUPLE_ELEM(5, TYPE_DEF)


#define T_TYPE_IDENTIFIER(TYPE_DEF)\
BOOST_PP_TUPLE_ELEM(6, TYPE_DEF)


#define T_IFACE_TYPE(TYPE_DEF)\
BOOST_PP_TUPLE_ELEM(7, TYPE_DEF)


#define T_IS_TYPEDEF(TYPE_DEF)\
BOOST_PP_EQUAL(T_TYPE_IDENTIFIER(TYPE_DEF), CT_TYPEDEF_IDENTIFIER)


#define T_IS_CLASSDEF(TYPE_DEF)\
BOOST_PP_EQUAL(T_TYPE_IDENTIFIER(TYPE_DEF), CT_CLASSDEF_IDENTIFIER)


#define T_IS_ENUMDEF(TYPE_DEF)\
BOOST_PP_EQUAL(T_TYPE_IDENTIFIER(TYPE_DEF), CT_ENUMDEF_IDENTIFIER)


#define T_IS_TYPEDEF_ALIAS(TYPE_DEF)\
BOOST_PP_EQUAL(T_TYPE_IDENTIFIER(TYPE_DEF), CT_TYPEDEF_ALIAS_IDENTIFIER)


#define T_IS_CLASSDEF_ALIAS(TYPE_DEF)\
BOOST_PP_EQUAL(T_TYPE_IDENTIFIER(TYPE_DEF), CT_CLASSDEF_ALIAS_IDENTIFIER)


#define T_IS_ENUMDEF_ALIAS(TYPE_DEF)\
BOOST_PP_EQUAL(T_TYPE_IDENTIFIER(TYPE_DEF), CT_ENUMDEF_ALIAS_IDENTIFIER)


// NOTE GENERIC METHODS
#define T_NAMESPACE(NAMETUPLE)\
BOOST_PP_TUPLE_ELEM(0, NAMETUPLE)


#define T_NAME(NAMETUPLE)\
BOOST_PP_TUPLE_ELEM(1, NAMETUPLE)


#define T_QUALNAME(NAMETUPLE)\
T_NAMESPACE(NAMETUPLE)::T_NAME(NAMETUPLE)


#define T_REG_QUALIFIED_NAME(TYPE_DEF)\
BOOST_PP_STRINGIZE(T_NAMESPACE(T_NAMETUPLE(TYPE_DEF)).T_NAME(T_NAMETUPLE(TYPE_DEF)))


#define T_REGISTERED_TYPE(TYPE_DEF)\
BOOST_PP_IF(\
    T_TYPE_IDENTIFIER(TYPE_DEF),\
    py::type::of<T_QUALNAME(T_NAMETUPLE(TYPE_DEF))>(),\
    py::type::of<T_QUALNAME(T_NAMETUPLE(T_BASE(TYPE_DEF)))>()\
)


#define T_QUALIFIED_UNDERLYING_CLASS(TYPE_DEF)\
T_QUALNAME(T_BASE_PRIMITIVE(TYPE_DEF))


#define T_UNQUALIFIED_UNDERLYING_CLASS(TYPE_DEF)\
T_NAME(T_BASE_PRIMITIVE(TYPE_DEF))


// NOTE CLASS MEMBER DEFINITION METHODS
#define CM_NAME(CLASS_MEMBER)\
BOOST_PP_TUPLE_ELEM(1, CLASS_MEMBER)


#define CM_TYPE(CLASS_MEMBER)\
BOOST_PP_TUPLE_ELEM(0, CLASS_MEMBER)


#define CM_IS_OPTIONAL(CLASS_MEMBER)\
T_IS_OPTIONAL(CM_TYPE(CLASS_MEMBER))


// NOTE CLASS DEFINITION METHODS
#define C_ALL_MEMBERS(CLASS_DEF)\
BOOST_PP_SEQ_CAT((T_MACRO_NAME(CLASS_DEF))(_MEMBERS))


// NOTE TYPE DEFINITION METHODS
#define T_CONSTRUCTORS(TYPE_DEF)\
BOOST_PP_CAT(T_MACRO_NAME(TYPE_DEF), _CONSTRUCTORS)


// NOTE ALIAS DEFINITION METHODS
#define T_ALIAS_INHERITANCE_CHAIN(ALIAS_DEF)\
BOOST_PP_CAT(T_MACRO_NAME(ALIAS_DEF), _INHERITANCE_CHAIN)


#define T_ALIAS_ORIGIN(ALIAS_DEF)\
BOOST_PP_SEQ_HEAD(T_ALIAS_INHERITANCE_CHAIN(ALIAS_DEF))


// NOTE ENUMS
#define ENUM_MEMBER(NAME)\
    NAME


// NOTE DATACLASSES
#define DATACLASS_MEMBER(BASE_TP, NAME)(\
    BASE_TP,\
    NAME\
)


#define NONE BOOST_PP_EMPTY()


#define DATACLASS_DEFINITION(NAME, CLS, MEMBERS, BASES, IFACE_CLS)(\
    NAME,\
    CLS,\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    MEMBERS,\
    BASES,\
    CT_CLASSDEF_IDENTIFIER,\
    IFACE_CLS\
)


#define ENUM_DEFINITION(NAME, CLS, MEMBERS, IFACE_CLS)(\
    NAME,\
    CLS,\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    MEMBERS,\
    BOOST_PP_EMPTY(),\
    CT_ENUMDEF_IDENTIFIER,\
    IFACE_CLS\
)


// NOTE TYPES
#define TYPE_DEFINITION(NAME, CLS, BASE, T_PY_BASE, IFACE_CLS)(\
    NAME,\
    CLS,\
    BASE,\
    T_PY_BASE,\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    CT_TYPEDEF_IDENTIFIER,\
    IFACE_CLS\
)


// NOTE ALIAS
#define TYPE_DEFINITION_ALIAS(NAME, CLS, BASE, IFACE_CLS)(\
    NAME,\
    CLS,\
    T_BASE_PRIMITIVE(BASE),\
    T_PY_PRIMITIVE(BASE),\
    BOOST_PP_EMPTY(),\
    BASE,\
    CT_TYPEDEF_ALIAS_IDENTIFIER,\
    IFACE_CLS\
)


#define ENUM_DEFINITION_ALIAS(NAME, CLS, BASE, IFACE_CLS)(\
    NAME,\
    CLS,\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BASE,\
    CT_ENUMDEF_ALIAS_IDENTIFIER,\
    IFACE_CLS\
)


#define DATACLASS_DEFINITION_ALIAS(NAME, CLS, BASE, IFACE_CLS)(\
    NAME,\
    CLS,\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BASE,\
    CT_CLASSDEF_ALIAS_IDENTIFIER,\
    IFACE_CLS\
)


// NOTE CONTAINERS
#define STD_VECTOR(TYPE_DEF)(\
    STD_VECTOR,\
    (std, vector<T_QUALNAME(T_NAMETUPLE(TYPE_DEF))>),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    TYPE_DEF,\
    CT_STD_VECTOR_IDENTIFIER,\
    (std, vector<T_QUALNAME(T_IFACE_TYPE(TYPE_DEF))>)\
)


#define STD_OPTIONAL(TYPE_DEF)(\
    STD_OPTIONAL,\
    (std, optional<T_QUALNAME(T_NAMETUPLE(TYPE_DEF))>),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    TYPE_DEF,\
    CT_STD_OPTIONAL_IDENTIFIER,\
    (std, optional<T_QUALNAME(T_IFACE_TYPE(TYPE_DEF))>)\
)


#define STD_DEQUE(TYPE_DEF)(\
    STD_DEQUE,\
    (std, deque<T_QUALNAME(T_NAMETUPLE(TYPE_DEF))>),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    TYPE_DEF,\
    CT_STD_DEQUE_IDENTIFIER,\
    (std, deque<T_QUALNAME(T_IFACE_TYPE(TYPE_DEF))>)\
)


#endif
