#include "core_types/macros/register/instanceable.hpp"
#include "test_app/types.hpp"
#include "test_app/definition.hpp"


CT_CLASSDEF_REGISTER_SUBCLASS_REG(TEST_APP_AUTHOR);
CT_CLASSDEF_REGISTER_SUBCLASS_REG(TEST_APP_AUTHORED);
CT_CLASSDEF_REGISTER_SUBCLASS_REG(TEST_APP_WITH_TIMESTAMPS);
CT_ENUMDEF_REGISTER_SUBCLASS_REG(TEST_APP_POST_STATUS);
CT_CLASSDEF_REGISTER_SUBCLASS_REG(TEST_APP_POST);
CT_CLASSDEF_REGISTER_SUBCLASS_REG(TEST_APP_COMMENT);
CT_CLASSDEF_REGISTER_SUBCLASS_REG(TEST_APP_COMMENT_POST);
CT_ALIASDEF_REGISTER_SUBCLASS_REG(TEST_APP_DOMAIN);
CT_CLASSDEF_REGISTER_SUBCLASS_REG(TEST_APP_NO_MEMBERS);


