#include "base_types/macros/register.hpp"
#include "test_app/types.hpp"
#include "test_app/definition.hpp"


PY_CLASSDEF_DECLARE_SUBCLASS_REG(TEST_APP_AUTHOR);
PY_CLASSDEF_DECLARE_SUBCLASS_REG(TEST_APP_AUTHORED);
PY_CLASSDEF_DECLARE_SUBCLASS_REG(TEST_APP_WITH_TIMESTAMPS);
PY_ENUMDEF_DECLARE_SUBCLASS_REG(TEST_APP_POST_STATUS);
PY_CLASSDEF_DECLARE_SUBCLASS_REG(TEST_APP_POST);
PY_CLASSDEF_DECLARE_SUBCLASS_REG(TEST_APP_COMMENT);
PY_CLASSDEF_DECLARE_SUBCLASS_REG(TEST_APP_COMMENT_POST);
PY_ALIASDEF_DECLARE_SUBCLASS_REG(TEST_APP_DOMAIN);
