#ifndef CORE_TYPES_MACROS_BACKEND
#define CORE_TYPES_MACROS_BACKEND
#include "core_types/macros/definition.hpp"
#include "core_types/macros/declaration.hpp"


#define CPP_CLASSDEF_DECLARATION(CLASS_DEF)\
struct T_NAME(T_NAMETUPLE(CLASS_DEF))\
    BOOST_PP_TUPLE_ENUM(BOOST_PP_IF(\
        BOOST_PP_IS_EMPTY(T_BASE(CLASS_DEF)),\
        (BOOST_PP_EMPTY()),\
        (: BOOST_PP_SEQ_ENUM(BOOST_PP_SEQ_FOR_EACH(CL_INHERIT_BASE, BOOST_PP_EMPTY(), T_BASE(CLASS_DEF)))))\
    )\
{\
    using TupleType = std::tuple<BOOST_PP_SEQ_FOR_EACH_I(CL_MEMBER_TYPE, BOOST_PP_EMPTY(), C_ALL_MEMBERS(CLASS_DEF))>;\
    BOOST_PP_SEQ_FOR_EACH(CL_MEMBER_DECLARATION, BOOST_PP_EMPTY(), T_MEMBERS(CLASS_DEF))\
\
    T_NAME(T_NAMETUPLE(CLASS_DEF)) (\
    ) \
    BOOST_PP_TUPLE_ENUM(BOOST_PP_IF(\
        BOOST_PP_IS_EMPTY(T_BASE(CLASS_DEF)),\
        (BOOST_PP_EMPTY()),\
        (: BOOST_PP_SEQ_FOR_EACH_I(CL_INITIALIZE_EMPTY_BASE, BOOST_PP_EMPTY(), T_BASE(CLASS_DEF)))\
    ))\
    {}\
\
    T_NAME(T_NAMETUPLE(CLASS_DEF)) (\
        BOOST_PP_SEQ_FOR_EACH_I(CL_MEMBER_ARGUMENT, BOOST_PP_EMPTY(), C_ALL_MEMBERS(CLASS_DEF))\
    ) : \
    BOOST_PP_TUPLE_ENUM(BOOST_PP_IF(\
        BOOST_PP_IS_EMPTY(T_BASE(CLASS_DEF)),\
        (BOOST_PP_EMPTY()),\
        (BOOST_PP_SEQ_FOR_EACH_I(CL_INITIALIZE_BASE, BOOST_PP_EMPTY(), T_BASE(CLASS_DEF)))\
    ))\
    BOOST_PP_COMMA_IF(BOOST_PP_AND(\
        BOOST_PP_NOT(BOOST_PP_IS_EMPTY(T_BASE(CLASS_DEF))),\
        BOOST_PP_NOT(BOOST_PP_IS_EMPTY(T_MEMBERS(CLASS_DEF)))\
    ))\
    BOOST_PP_SEQ_FOR_EACH_I(CM_INITIALIZE, BOOST_PP_EMPTY(), T_MEMBERS(CLASS_DEF))\
    {}\
\
    T_NAME(T_NAMETUPLE(CLASS_DEF)) (const T_NAME(T_NAMETUPLE(CLASS_DEF))& other)\
    : \
    BOOST_PP_TUPLE_ENUM(BOOST_PP_IF(\
        BOOST_PP_IS_EMPTY(T_BASE(CLASS_DEF)),\
        (BOOST_PP_EMPTY()),\
        (BOOST_PP_SEQ_FOR_EACH_I(CL_INITIALIZE_BASE_COPY, other, T_BASE(CLASS_DEF)))\
    ))\
    BOOST_PP_COMMA_IF(BOOST_PP_AND(\
        BOOST_PP_NOT(BOOST_PP_IS_EMPTY(T_BASE(CLASS_DEF))),\
        BOOST_PP_NOT(BOOST_PP_IS_EMPTY(T_MEMBERS(CLASS_DEF)))\
    ))\
    BOOST_PP_SEQ_FOR_EACH_I(CM_INITIALIZE, other, T_MEMBERS(CLASS_DEF))\
    {}\
\
    T_NAME(T_NAMETUPLE(CLASS_DEF))& operator=(const T_NAME(T_NAMETUPLE(CLASS_DEF))& other) {\
        BOOST_PP_SEQ_FOR_EACH(CM_COPY, other, C_ALL_MEMBERS(CLASS_DEF))\
        return *this;\
    }\
    TupleType as_tuple() const\
    {\
        return std::make_tuple(BOOST_PP_SEQ_FOR_EACH_I(CL_MEMBER_NAME, BOOST_PP_EMPTY(), C_ALL_MEMBERS(CLASS_DEF)));\
    }\
}


#define CPP_ENUMDEF_DECLARATION(ENUM_DEF)\
enum T_NAME(T_NAMETUPLE(ENUM_DEF)) {\
    BOOST_PP_SEQ_ENUM(T_MEMBERS(ENUM_DEF))\
}


#define CPP_ALIASDEF_DECLARATION(ALIAS_DEF)\
typedef T_QUALNAME(T_NAMETUPLE(T_BASE(ALIAS_DEF))) T_NAME(T_NAMETUPLE(ALIAS_DEF))


#define CPP_TYPEDEF_DECLARATION(TYPE_DEF)\
typedef T_QUALNAME(T_BASE_PRIMITIVE(TYPE_DEF)) T_NAME(T_NAMETUPLE(TYPE_DEF))

#endif
