#ifndef BASE_TYPES_DEFINITION_BASE
#define BASE_TYPES_DEFINITION_BASE


#include <boost/preprocessor.hpp>
#include <boost/preprocessor/iteration/iterate.hpp>
#include <boost/preprocessor/facilities/empty.hpp> 
#include <boost/preprocessor/stringize.hpp>
#include <boost/preprocessor/cat.hpp>


// NOTE TYPE DEFINITION METHODS
#define T_MACRO_NAME(TYPE_DEF)\
BOOST_PP_TUPLE_ELEM(0, TYPE_DEF)


#define T_NAMETUPLE(TYPE_DEF)\
BOOST_PP_TUPLE_ELEM(1, TYPE_DEF)


#define T_BASE_PRIMITIVE(TYPE_DEF)\
BOOST_PP_TUPLE_ELEM(2, TYPE_DEF)


#define T_PY_PRIMITIVE(TYPE_DEF)\
BOOST_PP_TUPLE_ELEM(3, TYPE_DEF)


#define T_MEMBERS(TYPE_DEF)\
BOOST_PP_TUPLE_ELEM(4, TYPE_DEF)


#define T_BASE(TYPE_DEF)\
BOOST_PP_TUPLE_ELEM(5, TYPE_DEF)


#define T_IS_OPTIONAL(TYPE_DEF)\
BOOST_PP_TUPLE_ELEM(6, TYPE_DEF)


// NOTE GENERIC METHODS
#define T_NAMESPACE(NAMETUPLE)\
BOOST_PP_TUPLE_ELEM(0, NAMETUPLE)


#define T_NAME(NAMETUPLE)\
BOOST_PP_TUPLE_ELEM(1, NAMETUPLE)


#define T_QUALNAME(NAMETUPLE)\
T_NAMESPACE(NAMETUPLE)::T_NAME(NAMETUPLE)


#define T_REG_QUALIFIED_NAME(TYPE_DEF)\
BOOST_PP_STRINGIZE(T_NAMESPACE(T_NAMETUPLE(TYPE_DEF)).T_NAME(T_NAMETUPLE(TYPE_DEF)))


#define T_REGISTERED_TYPE(TYPE_DEF)\
py::type::of<T_QUALNAME(T_NAMETUPLE(TYPE_DEF))>()
//T_QUALNAME(T_NAMETUPLE(TYPE_DEF))::subclass_registry.get_py_cls(T_REG_QUALIFIED_NAME(TYPE_DEF))



// NOTE CLASS MEMBER DEFINITION METHODS
#define CM_NAME(CLASS_MEMBER)\
BOOST_PP_TUPLE_ELEM(1, CLASS_MEMBER)


#define CM_TYPE(CLASS_MEMBER)\
BOOST_PP_TUPLE_ELEM(0, CLASS_MEMBER)


#define CM_IS_OPTIONAL(CLASS_MEMBER)\
T_IS_OPTIONAL(CM_TYPE(CLASS_MEMBER))


// NOTE CLASS DEFINITION METHODS
#define C_ALL_MEMBERS(CLASS_DEF)\
BOOST_PP_SEQ_CAT((T_MACRO_NAME(CLASS_DEF))(_MEMBERS))


// NOTE TYPE DEFINITION METHODS
#define T_CONSTRUCTORS(TYPE_DEF)\
BOOST_PP_CAT(T_MACRO_NAME(TYPE_DEF), _CONSTRUCTORS)


// NOTE ALIAS DEFINITION METHODS
#define T_ALIAS_INHERITANCE_CHAIN(ALIAS_DEF)\
BOOST_PP_CAT(T_MACRO_NAME(ALIAS_DEF), _INHERITANCE_CHAIN)


#define T_ALIAS_ORIGIN(ALIAS_DEF)\
BOOST_PP_SEQ_HEAD(T_ALIAS_INHERITANCE_CHAIN(ALIAS_DEF))


// NOTE DATACLASSES
#define DATACLASS_MEMBER(BASE_TP, NAME)(\
    BASE_TP,\
    NAME\
)


#define DATACLASS_DEFINITION(NAME, CLS, MEMBERS, BASES)(\
    NAME,\
    CLS,\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    MEMBERS,\
    BASES,\
    0\
)


#define NO_BASES_DATACLASS_DEFINITION(NAME, CLS, MEMBERS)\
DATACLASS_DEFINITION(NAME, CLS, MEMBERS, BOOST_PP_EMPTY())


// NOTE ENUMS
#define ENUM_MEMBER(NAME)\
    NAME


#define ENUM_QUALIFIED_UNDERLYING_CLASS(ENUM_DEF)\
BOOST_PP_TUPLE_ELEM(2, ENUM_DEF)


#define ENUM_UNQUALIFIED_UNDERLYING_CLASS(ENUM_DEF)\
BOOST_PP_CAT(T_NAME(T_NAMETUPLE(ENUM_DEF)), _enum)


#define ENUM_MEMBERS(ENUM_DEF)\
BOOST_PP_TUPLE_ELEM(4, ENUM_DEF)


#define ENUM_DEFINITION(NAME, CLS, MEMBERS)(\
    NAME,\
    CLS,\
    BOOST_PP_CAT(T_QUALNAME(CLS), _enum),\
    BOOST_PP_EMPTY(),\
    MEMBERS,\
    BOOST_PP_EMPTY(),\
    0\
)


// NOTE TYPES
#define TYPE_DEFINITION(NAME, CLS, BASE_PRIMITIVE, LINK_PRIMITIVE)(\
    NAME,\
    CLS,\
    BASE_PRIMITIVE,\
    LINK_PRIMITIVE,\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    0\
)


// NOTE ALIAS
#define TYPE_DEFINITION_ALIAS(NAME, CLS, BASE)(\
    NAME,\
    CLS,\
    T_BASE_PRIMITIVE(BASE),\
    T_PY_PRIMITIVE(BASE),\
    BOOST_PP_EMPTY(),\
    BASE,\
    0\
)


#define ENUM_DEFINITION_ALIAS(NAME, CLS, BASE)(\
    NAME,\
    CLS,\
    T_BASE_PRIMITIVE(BASE),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BASE,\
    0\
)


#define DATACLASS_DEFINITION_ALIAS(NAME, CLS, BASE)(\
    NAME,\
    CLS,\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BASE,\
    0\
)


// NOTE CONTAINERS
#define STD_VECTOR(TYPE_DEF)(\
    STD_VECTOR,\
    (std, vector<T_QUALNAME(T_NAMETUPLE(TYPE_DEF))>),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    TYPE_DEF,\
    0\
)


#define STD_OPTIONAL(TYPE_DEF)(\
    STD_OPTIONAL,\
    (std, optional<T_QUALNAME(T_NAMETUPLE(TYPE_DEF))>),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    BOOST_PP_EMPTY(),\
    TYPE_DEF,\
    1\
)


#endif
